const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Azamat",
      email: "jumabekov@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "snow@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Polo Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 170,
      countInStock: 7,
      brand: "Polo",
      rating: 4.5,
      numReviews: 39,
      description: "high quality product",
    },
    {
      name: "Mavi Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 5,
      brand: "Mavi",
      rating: 4.5,
      numReviews: 77,
      description: "brand new product",
    },
    {
      name: "Lacoste Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 190,
      countInStock: 2,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 107,
      description: "new collection product",
    },
    {
      name: "Polo Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 12,
      brand: "Polo",
      rating: 4.1,
      numReviews: 74,
      description: "fit pantalons",
    },
    {
      name: "Denim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 140,
      countInStock: 6,
      brand: "Denim",
      rating: 4.4,
      numReviews: 100,
      description: "nylon pants",
    },
    {
      name: "D&G Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 185,
      countInStock: 5,
      brand: "D&G",
      rating: 4.7,
      numReviews: 43,
      description: "slim fit pants",
    },
  ],
};

module.exports = data;
