const data = {
  products: [
    {
      _id: "1",
      name: "Polo Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 170,
      countInStock: 20,
      brand: "Polo",
      rating: 4.5,
      numReviews: 39,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Mavi Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 0,
      brand: "Mavi",
      rating: 4.5,
      numReviews: 77,
      description: "brand new product",
    },
    {
      _id: "3",
      name: "Lacoste Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 190,
      countInStock: 2,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 107,
      description: "new collection product",
    },
    {
      _id: "4",
      name: "Polo Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 12,
      brand: "Polo",
      rating: 4.1,
      numReviews: 74,
      description: "fit pantalons",
    },
    {
      _id: "5",
      name: "Denim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 140,
      countInStock: 0,
      brand: "Denim",
      rating: 4.4,
      numReviews: 100,
      description: "nylon pants",
    },
    {
      _id: "6 ",
      name: "D&G Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 185,
      countInStock: 5,
      brand: "D&G",
      rating: 4.7,
      numReviews: 43,
      description: "slim fit pants",
    },
  ],
};

module.exports = data;
